'use strict';
const E=window.ExamEngine,B=window.CREP_BANK,app=document.getElementById('app');
const names=['QCM théorique','Pratique terrain','Questions ouvertes'];
const key='crep-examen-session-v1';
let s=null,reviewTab=0,saveFailed=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n.toLocaleString('fr-FR',{maximumFractionDigits:2});
try{const stored=JSON.parse(sessionStorage.getItem(key));if(stored&&stored.version===1&&stored.phases?.length===3&&stored.phases.every(p=>p.length===40)&&['exam','grading','results'].includes(stored.stage))s=stored;}catch{}
function save(){try{if(s)sessionStorage.setItem(key,JSON.stringify(s));else sessionStorage.removeItem(key);saveFailed=false;}catch{saveFailed=true;}}
function references(q){return `<div class="reference">Support de cours · ${q.pages.map(p=>`<a href="cours.pdf#page=${p}" target="_blank" rel="noopener">p. ${p} ↗</a>`).join('')}</div>`;}
function base(content){const active=s?.stage==='exam'?s.phase:s?.stage==='grading'?2:-1;
 app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><svg viewBox="0 0 40 40" aria-hidden="true"><rect width="40" height="40" rx="10" fill="#c4e7a8"/><path d="M11 28V16l9-7 9 7v12M16 28v-9h8v9" fill="none" stroke="#1b302b" stroke-width="2.2"/></svg><div>CREP<span aria-hidden="true">.</span><small>EXAMENS BLANCS</small></div></div><div class="side-label">VOTRE PARCOURS</div><div class="steps">${names.map((n,i)=>`<div class="step ${active===i||!s&&i===0?'active':''}"><span class="num">${s?.submitted[i]?'✓':String(i+1).padStart(2,'0')}</span><div><strong>${n}</strong><small>40 questions · sur 20</small></div></div>`).join('')}</div><div class="side-bottom"><div class="source-label">VOTRE SUPPORT</div><p>Plomb sans mention<br>Le Centre F<br>Septembre 2026 · Révision 02</p><div class="rule"><b>11/20</b><br>minimum à chaque phase</div></div></aside><main class="workspace"><header class="topbar"><strong>Formation diagnostic immobilier <span class="mobile-hide">/ Plomb</span></strong><span><span class="dot"></span>Entraînement personnel</span></header>${saveFailed?'<p class="save-warning" role="status">La sauvegarde dans cet onglet est indisponible. Gardez cette page ouverte jusqu’à la fin.</p>':''}${content}</main></div>`;
 bind();
}
function home(){base(`<section class="intro"><div><span class="eyebrow">LE DIAGNOSTIC PLOMB, EN CONDITIONS D’EXAMEN</span><h1>À vous de jouer.</h1><p>Trois phases pour mettre vos connaissances à l’épreuve.<br>Un nouveau tirage à chaque examen, à partir de votre cours.</p></div><div class="stamp"><b>120</b><span>QUESTIONS</span></div></section><section class="phase-cards" aria-label="Les trois phases"><article class="phase-card"><div class="label"><span>PHASE 01</span><span class="icon" aria-hidden="true">☷</span></div><h3>QCM théorique</h3><p>Une ou plusieurs réponses, toujours précisées. Correction automatique.</p><div class="metric"><b>40</b><span>sur ${B.qcm.length} questions</span></div></article><article class="phase-card"><div class="label"><span>PHASE 02</span><span class="icon" aria-hidden="true">⌂</span></div><h3>Pratique terrain</h3><p>Des situations de diagnostic à résoudre par choix de décisions. Correction automatique.</p><div class="metric"><b>40</b><span>sur ${B.practical.length} cas</span></div></article><article class="phase-card"><div class="label"><span>PHASE 03</span><span class="icon" aria-hidden="true">✎</span></div><h3>Questions ouvertes</h3><p>Rédigez vos réponses, puis évaluez-les avec le corrigé et son barème détaillé.</p><div class="metric"><b>40</b><span>sur ${B.open.length} questions</span></div></article></section><section class="start-panel"><div><h3>Votre prochain examen commence ici.</h3><p>40 questions par phase · Sans chronomètre imposé · Aucun doublon dans une phase</p></div><button class="light" data-action="start">Commencer l’examen <span aria-hidden="true">↗</span></button></section><section class="details-grid"><div><h3>Une validation dans les trois phases</h3><p>Chaque phase est notée sur 20. Il faut au moins <b>11/20 dans chacune</b> : une bonne note ne compense pas une phase insuffisante.</p></div><div><h3>Un barème clair, jusqu’au corrigé</h3><p>QCM et terrain : 1 point si la sélection est entièrement exacte, sinon 0, sans pénalité. Ouvertes : 2 critères de 0,5 point, à évaluer par vous ou un formateur. La somme sur 40 est divisée par 2.</p></div></section><p class="bottom-note">Questions rédigées à partir de « CREP sans Mention V02 septembre 2026 ». Corrigés et pages du cours disponibles après les épreuves. Les cas terrain sont des simulations écrites. Ce résultat d’entraînement ne constitue pas une certification officielle.<br>Votre session reste dans cet onglet après actualisation ; elle n’est pas synchronisée entre appareils. Fermer l’onglet peut l’effacer.</p>`);}
function count(i){return s.phases[i].filter(q=>E.answered(q,s.answers[q.id])).length;}
function nav(phase,grading=false){const list=s.phases[phase],done=grading?list.filter(q=>s.grades[q.id]!=null).length:count(phase);return `<aside class="navigator" aria-label="Navigation des questions"><h3>${grading?'Correction':'Questions'} de la phase</h3><div class="grid-numbers">${list.map((q,i)=>`<button type="button" data-action="goto" data-index="${i}" class="${i===s.index?'current':''} ${(grading?s.grades[q.id]!=null:E.answered(q,s.answers[q.id]))?'done':''} ${s.flags[q.id]?'flagged':''}" aria-label="Question ${i+1}${(grading?s.grades[q.id]!=null:E.answered(q,s.answers[q.id]))?', '+(grading?'évaluée':'répondue'):''}${s.flags[q.id]?', à revoir':''}" ${i===s.index?'aria-current="step"':''}>${i+1}</button>`).join('')}</div><div class="legend">Vert : ${grading?'évaluée':'répondue'}<br>${grading?'':'Point orange : à revoir<br>'}Contour : question actuelle</div><div class="nav-summary"><b id="nav-count">${done}</b> / 40 ${grading?'évaluées':'répondues'}<div class="progress"><span id="nav-progress" style="width:${done/40*100}%"></span></div></div></aside>`;}
function render(){if(!s)return home();if(s.stage==='exam')exam();else if(s.stage==='grading')grading();else results();}
function exam(){const q=s.phases[s.phase][s.index],a=s.answers[q.id],multi=q.correct?.length>1;
 base(`<div class="exam-heading"><div><span class="eyebrow">PHASE ${String(s.phase+1).padStart(2,'0')} SUR 03</span><h1>${names[s.phase]}</h1></div><span class="badge">Objectif : 11/20 minimum</span></div><div class="exam-layout"><div class="question-area"><section class="question-card" aria-labelledby="question-title"><div class="question-meta"><span>QUESTION ${String(s.index+1).padStart(2,'0')} / 40</span><span>${esc(q.topic)}</span></div>${q.context?`<div class="scenario"><strong>${esc(q.title)}</strong>${esc(q.context)}</div>`:''}<h2 id="question-title" tabindex="-1">${esc(q.prompt)}</h2><p class="answer-hint">${q.options?(multi?`<span class="badge warn">Plusieurs réponses attendues · ${q.correct.length} réponses</span>`:'Une seule réponse attendue'):'Réponse rédigée · 2 critères de 0,5 point à évaluer après l’épreuve.'}</p>${q.options?`<div class="options" role="group" aria-labelledby="question-title">${q.order.map((v,i)=>`<label class="option"><input type="${multi?'checkbox':'radio'}" name="answer" value="${v}" ${a?.includes(v)?'checked':''}><span>${esc(q.options[v])}</span><em>${String.fromCharCode(65+i)}</em></label>`).join('')}</div>`:`<label class="sr-only" for="written">Votre réponse</label><textarea id="written" placeholder="Développez votre réponse ici…" maxlength="12000">${esc(a??'')}</textarea><div class="below"><span>Expliquez votre raisonnement avec vos propres mots.</span><span id="char-count">${(a??'').length} / 12 000</span></div>`}</section><div class="exam-actions"><button class="secondary" data-action="prev" ${s.index===0?'disabled':''}>← Précédente</button>${s.index<39?'<button data-action="next">Suivante →</button>':'<button data-action="submit">Terminer cette phase →</button>'}</div><div class="below"><button class="link" data-action="flag">${s.flags[q.id]?'● Marquée à revoir':'○ Marquer à revoir'}</button><button class="link" data-action="submit">Terminer la phase</button></div><p class="bottom-note">Les réponses restent modifiables jusqu’à la remise de cette phase. Les corrigés seront disponibles à la fin des trois phases.</p></div>${nav(s.phase)}</div>`);
 document.querySelectorAll('input[name="answer"]').forEach(input=>input.addEventListener('change',()=>{s.answers[q.id]=[...document.querySelectorAll('input[name="answer"]:checked')].map(e=>Number(e.value));save();updateCounts(q);}));
 document.getElementById('written')?.addEventListener('input',e=>{s.answers[q.id]=e.target.value;document.getElementById('char-count').textContent=`${e.target.value.length} / 12 000`;save();updateCounts(q);});
}
function updateCounts(q){const done=count(s.phase);document.getElementById('nav-count').textContent=done;document.getElementById('nav-progress').style.width=done/40*100+'%';const btn=document.querySelector(`.grid-numbers button[data-index="${s.index}"]`);btn.classList.toggle('done',E.answered(q,s.answers[q.id]));btn.setAttribute('aria-label',`Question ${s.index+1}${E.answered(q,s.answers[q.id])?', répondue':''}${s.flags[q.id]?', à revoir':''}`);}
function focusQuestion(){document.getElementById('question-title')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});}
function confirmAction(title,message,label,fn){const d=document.getElementById('confirm');document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-text').textContent=message;document.getElementById('dialog-confirm').textContent=label;d.returnValue='cancel';d.onclose=()=>{if(d.returnValue==='confirm')fn();};d.showModal();}
function submit(){const missing=40-count(s.phase),flags=s.phases[s.phase].filter(q=>s.flags[q.id]).length;confirmAction('Remettre cette phase ?',`${missing?`${missing} question${missing>1?'s':''} sans réponse : ${missing>1?'elles compteront':'elle comptera'} pour 0 point. `:'Vous avez répondu aux 40 questions. '}${flags?`${flags} question(s) marquée(s) à revoir. `:''}Après confirmation, les réponses de cette phase ne seront plus modifiables.`,s.phase<2?'Passer à la phase suivante':'Passer à la correction',()=>{s.submitted[s.phase]=true;if(s.phase<2){s.phase++;s.index=0;}else{s.stage='grading';s.index=0;s.phases[2].forEach(q=>{if(!E.answered(q,s.answers[q.id]))s.grades[q.id]=0;});const first=s.phases[2].findIndex(q=>s.grades[q.id]==null);s.index=first<0?0:first;}save();render();focusQuestion();});}
function grading(){const q=s.phases[2][s.index],blank=!E.answered(q,s.answers[q.id]),done=s.phases[2].every(q=>s.grades[q.id]!=null);
 base(`<div class="exam-heading"><div><span class="eyebrow">LES TROIS PHASES SONT TERMINÉES</span><h1>Évaluez vos réponses ouvertes.</h1></div><span class="badge">Correction guidée</span></div><p class="muted" style="font-size:13px;margin-bottom:24px">Comparez chaque réponse aux deux critères ci-dessous. Vous ou votre formateur attribuez la note : aucune analyse automatique du texte n’est utilisée. Chaque critère satisfait vaut 0,5 point.</p><div class="exam-layout"><div class="question-area"><section class="question-card"><div class="question-meta"><span>RÉPONSE ${s.index+1} / 40</span><span>${esc(q.topic)}</span></div><h2 id="question-title" tabindex="-1">${esc(q.prompt)}</h2><span class="eyebrow">VOTRE RÉPONSE</span><div class="student-answer" style="margin-top:12px">${blank?'Aucune réponse — 0 point.':esc(s.answers[q.id])}</div><div class="rubric"><h3>Éléments attendus · 0,5 point par critère</h3><ol>${q.rubric.map(r=>`<li>${esc(r)}</li>`).join('')}</ol></div>${references(q)}<h3 style="font-size:13px;margin-top:25px">Combien de critères votre réponse satisfait-elle ?</h3><div class="grade-options">${[0,.5,1].map((v,i)=>`<button data-action="grade" data-value="${v}" aria-pressed="${s.grades[q.id]===v}" class="${s.grades[q.id]===v?'selected':''}" ${blank?'disabled':''}><b>${fmt(v)}</b><small>${i===0?'Aucun critère':i===1?'Un critère sur deux':'Les deux critères'}<br>point${v===1?'':' possible(s)'}</small></button>`).join('')}</div></section><div class="exam-actions"><button class="secondary" data-action="prev" ${s.index===0?'disabled':''}>← Précédente</button>${s.index<39?'<button data-action="next">Suivante →</button>':'<button data-action="ungraded">Prochaine non évaluée →</button>'}</div><div class="footer-actions"><button class="light" data-action="finish" ${done?'':'disabled'}>Afficher le résultat sur 20 →</button>${!done?'<button class="link" data-action="ungraded">Aller à une réponse non évaluée</button>':''}</div><p class="bottom-note">Une réponse vide vaut 0. Pour une réponse rédigée, la note doit être choisie explicitement. Votre bilan indiquera que la phase ouverte a été évaluée manuellement.</p></div>${nav(2,true)}</div>`);
}
function reviewItem(q,i,phase){const a=s.answers[q.id],pt=phase<2?E.point(q,a):s.grades[q.id];return `<details class="review-item"><summary><span class="mark ${pt===1?'':'bad'}">${pt===1?'✓':pt===0?'×':'½'}</span><span><b>${String(i+1).padStart(2,'0')}.</b> ${esc(q.prompt)}</span><span class="muted" style="white-space:nowrap">${fmt(pt)} / 1</span></summary><div class="review-body">${q.context?`<div class="scenario"><strong>${esc(q.title)}</strong>${esc(q.context)}</div>`:''}<p><b>Votre réponse</b></p><div class="student-answer">${q.options?(Array.isArray(a)&&a.length?a.map(v=>esc(q.options[v])).join('<br>'):'Sans réponse'):esc(a||'Sans réponse')}</div>${q.options?`<p><b>Réponse${q.correct.length>1?'s':''} attendue${q.correct.length>1?'s':''}</b><br>${q.correct.map(v=>esc(q.options[v])).join('<br>')}</p><p class="muted">${esc(q.explanation)}</p>`:`<p><b>Barème · 0,5 point par critère</b></p><ol>${q.rubric.map(r=>`<li>${esc(r)}</li>`).join('')}</ol><p class="muted">Note attribuée manuellement : ${fmt(pt)} / 1.</p>`}${references(q)}</div></details>`;}
function results(){const notes=E.scores(s),pass=E.validated(notes),mean=notes.reduce((a,b)=>a+b,0)/3;const weak=notes.map((n,i)=>n<11?names[i]:null).filter(Boolean);
 base(`<section class="result-banner ${pass?'':'failed'}"><span class="eyebrow">BILAN DE VOTRE EXAMEN BLANC</span><h1>${pass?'Les trois phases sont validées.':'Encore un peu d’entraînement.'}</h1><p>${pass?'Vous avez atteint au moins 11/20 dans chaque phase.':`${weak.length} phase${weak.length>1?'s restent':' reste'} sous 11/20 : ${weak.join(', ')}.`}</p></section><div class="scores">${notes.map((n,i)=>`<article class="score"><h3>${names[i]}</h3><div class="value">${fmt(n)}<span> / 20</span></div><p>${fmt(n*2)} / 40 points · ${i<2?'Correction automatique':'Évaluation manuelle'}</p><span class="badge ${n<11?'fail':''}">${n>=11?'✓ Validée':'À retravailler'} · seuil 11/20</span></article>`).join('')}</div><p class="muted" style="font-size:13px">Moyenne indicative : <b>${fmt(mean)}/20</b>. La validation dépend de chaque phase, sans compensation.<br>Questions ouvertes : note évaluée par vous ou un formateur, selon le barème du cours.</p><div class="footer-actions"><button data-action="restart">Nouvel examen aléatoire ↗</button><button class="secondary" data-action="print">Imprimer / enregistrer le bilan PDF</button><button class="secondary" data-action="regrade">Revoir la notation ouverte</button></div><section class="review-section"><span class="eyebrow">COMPRENDRE POUR PROGRESSER</span><h2>Vos réponses, expliquées.</h2><div class="tabs" role="tablist" aria-label="Corrigés par phase">${names.map((n,i)=>`<button role="tab" aria-selected="${reviewTab===i}" aria-controls="review-list" id="tab-${i}" class="${reviewTab===i?'active':''}" data-action="tab" data-index="${i}">${n}</button>`).join('')}</div><div id="review-list" role="tabpanel" aria-labelledby="tab-${reviewTab}">${s.phases[reviewTab].map((q,i)=>reviewItem(q,i,reviewTab)).join('')}</div></section><p class="bottom-note">Support : CREP sans Mention V02 septembre 2026 · ${new Date(s.started).toLocaleDateString('fr-FR')} · 40 questions par phase.<br>Examen blanc personnel. Les cas terrain sont des simulations écrites ; ce bilan n’est pas une certification officielle.</p>`);
}
function bind(){app.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>{const action=el.dataset.action;
 if(action==='start'){s=E.create(B);save();render();focusQuestion();return;}
 if(action==='goto'){s.index=Number(el.dataset.index);save();render();focusQuestion();}
 if(action==='prev'||action==='next'){s.index=Math.max(0,Math.min(39,s.index+(action==='next'?1:-1)));save();render();focusQuestion();}
 if(action==='flag'){const q=s.phases[s.phase][s.index];s.flags[q.id]=!s.flags[q.id];save();render();}
 if(action==='submit')submit();
 if(action==='grade'){const q=s.phases[2][s.index];s.grades[q.id]=Number(el.dataset.value);save();render();}
 if(action==='ungraded'){const index=s.phases[2].findIndex(q=>s.grades[q.id]==null);if(index>=0){s.index=index;save();render();focusQuestion();}else{document.querySelector('[data-action="finish"]')?.focus();}}
 if(action==='finish'&&s.phases[2].every(q=>s.grades[q.id]!=null)){s.stage='results';save();render();window.scrollTo(0,0);}
 if(action==='tab'){reviewTab=Number(el.dataset.index);results();document.getElementById(`tab-${reviewTab}`)?.focus();}
 if(action==='print')window.print();
 if(action==='regrade'){s.stage='grading';s.index=0;save();render();window.scrollTo(0,0);}
 if(action==='restart')confirmAction('Lancer un nouvel examen ?', 'Le tirage et les réponses de cette session seront remplacés. Vous pouvez enregistrer le bilan en PDF avant de continuer.','Nouvel examen',()=>{s=E.create(B);reviewTab=0;save();render();focusQuestion();});
 }));}
// Read-only WebMCP mirrors the current visible progress without exposing hidden solutions.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_exam_progress',title:'Lire la progression CREP',description:'Lit la phase et le nombre de réponses de l’examen courant. Ne révèle pas les corrigés pendant les épreuves.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Aucun paramètre attendu.');return s?{stage:s.stage,phase:s.stage==='exam'?names[s.phase]:null,answered:s.phases.map((_,i)=>count(i)),scores:s.stage==='results'?E.scores(s):null}:{stage:'home'};}})).catch(()=>{});}catch{}}
render();
